services:
  java_app:
    container_name: api_the_sales_galleon
    image: juanba/backend/api-the-sales-galleon:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=db_the_sales_galleon
      - DB_USERNAME=JuanBM
      - DB_PASSWORD=juanbm
    depends_on:
      - localhost
  localhost:
    container_name: db_the_sales_galleon
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: JuanBM
      POSTGRES_PASSWORD: juanbm
      POSTGRES_DB: db_the_sales_galleon
